### ISSUE TITLE
Payload's SWC core needs to be updated or keepImportAssertions throws an error

### ISSUE THREAD

**Issue by hoyere** [manawiki/repay#14]
I upgraded both the main package.json but also the one under payload's in the node_modules and that got past the error

PS C:\Users\Owner\Desktop\app_programs\remixEFC\repay> yarn dev                         
yarn run v1.22.21
$ node -r ts-node/register --watch-path ./server.ts server.ts
(node:7324) ExperimentalWarning: Watch mode is an experimental feature and might change 
at any time
(Use `node --trace-warnings ...` to show where the warning was created)
C:\Users\Owner\Desktop\app_programs\remixEFC\repay\node_modules\ts-node\src\transpilers\swc.ts:259
      throw new Error(
            ^
Error: @swc/core threw an error when attempting to validate swc compiler options.
You may be using an old version of swc which does not support the options used by ts-node.
Try upgrading to the latest version of swc.
Error message from swc:
Failed to deserialize buffer as swc::config::Options
JSON: {"sourceMaps":true,"module":{"type":"commonjs","noInterop":false,"strictMode":true,"ignoreDynamic":false},"swcrc":false,"jsc":{"parser":{"syntax":"typescript","tsx":false,"dynamicImport":true,"importAssertions":true},"target":"es2022","transform":{"legacyDecorator":true,"react":{"throwIfNamespace":false,"useBuiltins":false,"runtime":"automatic"},"useDefineForClassFields":true},"keepClassNames":true,"experimental":{"keepImportAttributes":true,"emitAssertForImportAttributes":true}}}

Caused by:
    unknown field `keepImportAttributes`, expected one of `plugins`, `keepImportAssertions`, `cacheRoot`, `disableBuiltinTransformsForInternalTesting` at line 1 column 485     
    at createVariant (C:\Users\Owner\Desktop\app_programs\remixEFC\repay\node_modules\ts    at createSwcOptions (C:\Users\Owner\Desktop\app_programs\remixEFC\repay\node_modules\ts-node\src\transpilers\swc.ts:201:25)
    at create (C:\Users\Owner\Desktop\app_programs\remixEFC\repay\node_modules\ts-node\src\transpilers\swc.ts:54:41)
    at createTranspiler (C:\Users\Owner\Desktop\app_programs\remixEFC\repay\node_modules\ts-node\src\index.ts:784:16)
    at createTranspileOnlyGetOutputFunction (C:\Users\Owner\Desktop\app_programs\remixEFC\repay\node_modules\ts-node\src\index.ts:1341:28)
    at createFromPreloadedConfig (C:\Users\Owner\Desktop\app_programs\remixEFC\repay\node_modules\ts-node\src\index.ts:1404:34)
    at create (C:\Users\Owner\Desktop\app_programs\remixEFC\repay\node_modules\ts-node\src\index.ts:624:10)
    at Object.register (C:\Users\Owner\Desktop\app_programs\remixEFC\repay\node_modules\ts-node\src\index.ts:591:15)
    at Object.<anonymous> (C:\Users\Owner\Desktop\app_programs\remixEFC\repay\node_modules\ts-node\register\index.js:1:16)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
Failed running 'server.ts'

**Comment by TatisLois** [comment]
same issue

**Comment by xHomu** [comment]
Closed by https://github.com/manawiki/repay/commit/6ea9f556c028f07910834f9c25d055ac2c6299b3
