### ISSUE TITLE
APIError: beginTransaction called while no connection to the database exists

### ISSUE THREAD

**Issue by kwabe007** [manawiki/repay#19]
Hi, I'm not sure what I'm missing but I can't seem to get the template to work. When running `yarn dev` and trying to access localhost:3000 I get met with the error:

```
APIError: beginTransaction called while no connection to the database exists
    at Object.beginTransaction (/home/kwabe007/test/repay/node_modules/@payloadcms/db-mongodb/src/transactions/beginTransaction.ts:14:11)
    at initTransaction (/home/kwabe007/test/repay/node_modules/payload/src/utilities/initTransaction.ts:20:43)
    at find (/home/kwabe007/test/repay/node_modules/payload/src/collections/operations/find.ts:41:47)
    at find (/home/kwabe007/test/repay/node_modules/payload/src/collections/operations/local/find.ts:63:14)
    at BasePayload.find (/home/kwabe007/test/repay/node_modules/payload/src/payload.ts:118:12)
    at loader (/home/kwabe007/test/repay/app/routes/_index.tsx:6:31)
    at Object.callRouteLoaderRR (/home/kwabe007/test/repay/node_modules/@remix-run/server-runtime/dist/data.js:52:22)
    at handler (/home/kwabe007/test/repay/node_modules/@remix-run/server-runtime/dist/routes.js:54:20)
    at runHandler (/home/kwabe007/test/repay/node_modules/@remix-run/router/router.ts:3960:7)
    at callLoaderOrAction (/home/kwabe007/test/repay/node_modules/@remix-run/router/router.ts:4020:22) {
  data: null,
  isOperational: true,
  isPublic: false,
  status: 500
}
```

These are the steps I took:
- Clone repo
- Install dependencies with `yarn;`
- Setup a local mongo instance via docker (without authentication).
- Copy `.env.example` to `.env` with `MONGODB_URL=mongodb://localhost:27017/app` and `PAYLOAD_SECRET=secret`.
- Run `yarn dev`.

I also double checked that I could reach the mongo server with `mongosh mongodb://localhost:27017/app`. I can access it without problems. No idea what I'm doing wrong.

Running
Ubuntu 22.04.4 LTS
node 20.11.1
yarn 1.22.21

**Comment by kwabe007** [comment]
Figured it out. Somehow I used **MONGODB_URL** as the environment variable name instead of **MONGODB_URI** which is the correct one.
